### ISSUE TITLE
Getting errors in Angular 5

### ISSUE THREAD

**Issue by SuperDevGuru** [bootsoon/ng-circle-progress#35]
I am getting this error in Angular 5 now.
//------------------------------------------------------------
Object(...) is not a function.
//------------------------------------------------------------
It worked fine with version 1.0.0. Should I use 1.0.0 for later use in Angular 5?

**Comment by HctrM** [comment]
I'm getting the same error with Angular 5.2, Ionic 3.9.2 and ng-circular-progress on 1.1.0. It used to work just fine.

**Comment by NathanBlaise** [comment]
Wanted to chime in and mention I was also receiving a similar error. Seems to be a common issue, for now I have reverted to 1.0.0 and it works just fine.

**Comment by bootsoon** [comment]
@SuperDevGuru @HctrM @NathanBlaise 

Please update to rxjs@6.2.1 and rxjs-compat@6.2.1

```
    "ng-circle-progress": "^1.1.0",
    "rxjs": "^6.2.1",
    "rxjs-compat": "^6.2.1",
```

My fault, sorry.
